# -*- coding: utf-8 -*-
"""FaceDetectionProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fY6WF5lEXF32b0rGfB6_9rW24foaoC6s

Carregando Imagem
"""

import cv2
from google.colab import drive
from google.colab.patches import cv2_imshow
drive.mount('/content/drive')

imagem = cv2.imread('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Images/people1.jpg')
imagem = cv2.resize(imagem,(800,600))
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
cv2_imshow(imagem_cinza)

"""Detecção de Faces"""

detector_facial = cv2.CascadeClassifier('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Cascades/haarcascade_frontalface_default.xml')
deteccoes = detector_facial.detectMultiScale(imagem_cinza, scaleFactor=1.09)
for (x,y,w,h) in deteccoes:
  cv2.rectangle(imagem, (x,y), (x + w, y + h), (0,255,0), 5)
cv2_imshow(imagem)

imagem = cv2.imread('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Images/people2.jpg')
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
deteccoes = detector_facial.detectMultiScale(imagem_cinza, scaleFactor=1.2, minNeighbors=3, minSize=(32,32), maxSize=(100,100))
for (x,y,w,h) in deteccoes:
  print(w,h)
  cv2.rectangle(imagem, (x,y), (x + w, y + h), (0,255,0), 2)
cv2_imshow(imagem)

"""Detecção olhos"""

detector_olhos = cv2.CascadeClassifier('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Cascades/haarcascade_eye.xml')

imagem = cv2.imread('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Images/people1.jpg')
#imagem = cv2.resize(imagem, (800,600))
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
deteccoes = detector_facial.detectMultiScale(imagem_cinza, scaleFactor=1.3, minSize=(30,30))
for (x,y,w,h) in deteccoes:
  cv2.rectangle(imagem, (x,y), (x + w, y + h), (0,255,0), 2)

deteccoes_olhos = detector_olhos.detectMultiScale(imagem_cinza, scaleFactor=1.09, minNeighbors=10, maxSize=(70,70))
for(x, y, w, h) in deteccoes_olhos:
  print(w,h)
  cv2.rectangle(imagem, (x,y), (x + w, y + h), (0,0,255), 2)

cv2_imshow(imagem)